default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  sslmode: require
  host: <%= ENV['DATABASE_HOST'] %>
  database: <%= ENV['DATABASE_NAME'] %>
  username: <%= ENV['DATABASE_USER'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>

development:
  <<: *default

test:
  <<: *default

production:
  primary:
    <<: *default
  cache:
    <<: *default
  queue:
    <<: *default
  cable:
    <<: *default